'use strict';
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const vm = require('node:vm');
const assert = require('node:assert/strict');
test('renderer validates input and restores state after success, errors, and cancellation', async () => {
const ids = ['operation-panel','encode-tab','decode-tab','choose-file','file-name','file-detail','file-heading','file-limit','browse-label','password-heading','password','confirmation','confirmation-field','toggle-password','password-help','submit-button','submit-label','submit-arrow','spinner','status'];
const elements = Object.fromEntries(ids.map(id=>[id,{id,value:'',textContent:'',disabled:false,type:id==='password'||id==='confirmation'?'password':undefined,hidden:false,attrs:{},events:{},classList:{toggle(){}},setAttribute(k,v){this.attrs[k]=v;},addEventListener(k,handler){this.events[k]=handler;},focus(){document.activeElement=this;}}]));
const document={getElementById:id=>elements[id],querySelectorAll:()=>Object.values(elements).filter(x=>['encode-tab','decode-tab','choose-file','password','confirmation','toggle-password','submit-button'].includes(x.id))};
let chooseResponse={ok:true,file:{name:'source.txt',size:12}};
let resolveProcessing, calls=0;
const window={addEventListener(){},studio:{chooseInput:async()=>chooseResponse,process:()=>{calls++;return new Promise(resolve=>resolveProcessing=resolve);}}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname, '../src/renderer.js'),'utf8'),{window,document,TextEncoder});
const click=id=>elements[id].events.click();
const submit=()=>elements['operation-panel'].events.submit({preventDefault(){}});
 await submit(); assert.match(elements.status.textContent,/Choose a source/);
 await click('choose-file'); assert.equal(elements['file-name'].textContent,'source.txt');
 elements.password.value='tiny'; await submit(); assert.match(elements.status.textContent,/at least 12/);
 elements.password.value='strong-sample-password'; elements.confirmation.value='mismatch'; await submit(); assert.match(elements.status.textContent,/do not match/);
 elements.confirmation.value=elements.password.value;
 click('toggle-password');assert.equal(elements.password.type,'text');
 const pending=submit();assert.equal(elements.password.value,'');assert.equal(elements.confirmation.value,'');assert.equal(elements.password.type,'password');assert.equal(elements['submit-button'].disabled,true);
 await submit();assert.equal(calls,1);
 click('decode-tab');assert.equal(elements['confirmation-field'].hidden,false);
 resolveProcessing({ok:true,savedName:'encrypted.png'});await pending;assert.match(elements.status.textContent,/Saved encrypted/);assert.equal(elements['submit-button'].disabled,false);
 click('decode-tab');assert.equal(elements['confirmation-field'].hidden,true);assert.equal(elements['file-name'].textContent,'Choose an encrypted PNG');
 await click('choose-file');elements.password.value='wrong-password';let recover=submit();resolveProcessing({ok:false,message:'Wrong password or damaged encrypted PNG'});await recover;assert.match(elements.status.textContent,/Wrong password/);assert.equal(elements.password.value,'');
 elements.password.value='valid-password-again';recover=submit();resolveProcessing({ok:true,canceled:true});await recover;assert.match(elements.status.textContent,/Save canceled/);
 elements['decode-tab'].events.keydown({key:'ArrowLeft',preventDefault(){}});assert.equal(elements['encode-tab'].attrs['aria-selected'],'true');assert.equal(elements['file-name'].textContent,'source.txt');
 chooseResponse={ok:true,canceled:true};await click('choose-file');assert.equal(elements['file-name'].textContent,'source.txt');
 chooseResponse={ok:true,file:{name:'<img onerror=bad()>',size:0}};await click('choose-file');assert.equal(elements['file-name'].textContent,'<img onerror=bad()>');assert.match(elements['file-detail'].textContent,/0 bytes/);
});
